src/Web/VStoreAdvanceAdvance.Web.Administration/Controllers/LayouAdmintController.cs
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using System.Web.Mvc;
using VStore.Data.ViewModel.Layout;
using VStoreAdvance.Service.Sessions;

namespace VStoreAdvances.Web.Areas.Administration.Controllers
{
    public class LayoutAdminController : BaseController
    {
        /// <summary>
        /// The _user navigation manager.
        /// </summary>
        private readonly IUserNavigationManager _userNavigationManager;

        /// <summary>
        /// The _session app service.
        /// </summary>
        private readonly ISessionAppService _sessionAppService;

        /// <summary>
        /// The _multi tenancy config.
        /// </summary>
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        /// <summary>
        /// The _language manager.
        /// </summary>
        private readonly ILanguageManager _languageManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutController"/> class.
        /// </summary>
        /// <param name="userNavigationManager">
        /// The user navigation manager.
        /// </param>
        /// <param name="sessionAppService">
        /// The session app service.
        /// </param>
        /// <param name="multiTenancyConfig">
        /// The multi tenancy config.
        /// </param>
        /// <param name="languageManager">
        /// The language manager.
        /// </param>
        public LayoutAdminController(
            IUserNavigationManager userNavigationManager,
            ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
            _languageManager = languageManager;
        }

        /// <summary>
        /// The top menu.
        /// </summary>
        /// <param name="activeMenu">
        /// The active menu.
        /// </param>
        /// <returns>
        /// The <see cref="PartialViewResult"/>.
        /// </returns>
        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
            {
                MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                ActiveMenuItemName = activeMenu
            };

            return PartialView("_TopMenu", model);
        }

        /// <summary>
        /// The language selection.
        /// </summary>
        /// <returns>
        /// The <see cref="PartialViewResult"/>.
        /// </returns>
        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages()
            };

            return PartialView("_LanguageSelection", model);
        }

        /// <summary>
        /// The user menu or login link.
        /// </summary>
        /// <returns>
        /// The <see cref="PartialViewResult"/>.
        /// </returns>
        [ChildActionOnly]
        public PartialViewResult UserMenuOrLoginLink()
        {
            UserMenuOrLoginLinkViewModel model;

            if (AbpSession.UserId.HasValue)
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                };
            }
            else
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled
                };
            }

            return PartialView("_UserMenuOrLoginLink", model);
        }
    }
}

src/Web/VStoreAdvanceAdvance.Web.Administration/Views/Shared/_TopBar.cshtml
    <!-- mian-content -->
<div class="banner-content" id="home">
    <!-- header -->
    <header class="header">
        <div class="container-fluid px-lg-5">
            <!-- nav -->
            <nav class="py-4">
                <div id="logo">
                    <h1> <a href="index.html"><span>H</span>igh Edu</a></h1>
                </div>

                <label for="drop" class="toggle">Menu</label>
                <input type="checkbox" id="drop" />
                <ul class="menu mt-2">
                    @Html.Action("TopMenu", "LayoutAdmin", new { activeMenu = ViewBag.ActiveMenu })
                </ul>
                @*<ul class="nav navbar-nav navbar-right">
                        @Html.Action("LanguageSelection", "Layout")
                        @Html.Action("UserMenuOrLoginLink", "Layout")
                    </ul>*@
            </nav>
            <!-- //nav -->
        </div>
    </header>

    <!--/banner-->
    <div class="banner-info-w3pvt">
        <h3>Are you ready to apply?</h3>
        <p class="my-4">Lorem Ipsum is simply dummy text of the printing and typesetting industry has been the industry's standard dummy text ever since the 1500s, when an unknown printer.</p>

    </div>
    <!--// banner-inner -->
</div>